//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consulta_Dat_DocumentoDetalle_DocInternos
    {
        public int ID_DET_DOCUMENTO { get; set; }
        public int ID_DOCUMENTO { get; set; }
        public Nullable<int> ID_CAB_DET_DOCUMENTO { get; set; }
        public int OFICINA_DESTINO { get; set; }
        public string OBSERVACION { get; set; }
        public byte ID_EST_TRAMITE { get; set; }
        public string persona_num_documento { get; set; }
        public Nullable<bool> IND_01 { get; set; }
        public Nullable<bool> IND_02 { get; set; }
        public Nullable<bool> IND_03 { get; set; }
        public Nullable<bool> IND_04 { get; set; }
        public Nullable<bool> IND_05 { get; set; }
        public Nullable<bool> IND_06 { get; set; }
        public Nullable<bool> IND_07 { get; set; }
        public Nullable<bool> IND_08 { get; set; }
        public Nullable<bool> IND_09 { get; set; }
        public Nullable<bool> IND_10 { get; set; }
        public Nullable<bool> IND_11 { get; set; }
        public Nullable<System.DateTime> FECHA_RECEPCION { get; set; }
        public string INDICADORES { get; set; }
        public string USUARIO_RECEPCION { get; set; }
        public Nullable<System.DateTime> FECHA_ATENDIDO { get; set; }
        public string USUARIO_ATENDIDO { get; set; }
        public Nullable<System.DateTime> FECHA_ARCHIVO { get; set; }
        public string USUARIO_ARCHIVO { get; set; }
        public Nullable<System.DateTime> FECHA_DERIVADO { get; set; }
        public string USUARIO_DERIVADO { get; set; }
        public string USUARIO_CREA { get; set; }
        public System.DateTime FECHA_CREA { get; set; }
        public int OFICINA_CREA { get; set; }
        public string USUARIO_CANCELAR { get; set; }
        public Nullable<System.DateTime> FECHA_CANCELAR { get; set; }
        public string OBSERVACION_ARCHIVO { get; set; }
        public string OBSERVACION_ATENDIDO { get; set; }
        public string NOM_OFICINA_CREA { get; set; }
        public string NOM_OFICINA_DESTINO { get; set; }
        public Nullable<bool> FLAG_TIPO_MEMORANDO { get; set; }
        public Nullable<bool> FLAG_DESTINO_PRINCIPAL { get; set; }
    }
}
