//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consulta_Detalle_Documento_Externo
    {
        public int ID_DOC_DHCPA_DET { get; set; }
        public Nullable<int> ID_DOC_DHCPA { get; set; }
        public Nullable<int> ID_OFICINA_DIRECCION_DESTINO { get; set; }
        public string PERSONA_DESTINO { get; set; }
        public string ACTIVO { get; set; }
        public string NOMBRE_PERSONA_DESTINO { get; set; }
        public Nullable<bool> FLAG_TIPO_CARTA { get; set; }
        public string ENCARGADO { get; set; }
        public string CARGO { get; set; }
        public string OFICINA_EXTERNA { get; set; }
        public string OFICINA_SEDE { get; set; }
        public string DIRECCION_EXTERNO { get; set; }
    }
}
