//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESDOC.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAE_FIRMA_DIGITAL
    {
        public int ID_FIRMA_DIGITAL { get; set; }
        public Nullable<int> ID_DOCUMENTO { get; set; }
        public string PERSONA_FIRMAR { get; set; }
        public Nullable<int> ID_USUARIO_ENVIO { get; set; }
        public Nullable<bool> ESTADO_ENVIO { get; set; }
        public Nullable<System.DateTime> FECHA_FIRMA { get; set; }
        public Nullable<int> ID_UID_ALFRESCO { get; set; }
        public Nullable<bool> ESTADO_PERSONA_FIRMAR { get; set; }
    
        public virtual LOG_UID_ALFRESCO LOG_UID_ALFRESCO { get; set; }
        public virtual MAE_DOCUMENTO MAE_DOCUMENTO { get; set; }
        public virtual MAE_DOCUMENTO_DHCPA MAE_DOCUMENTO_DHCPA { get; set; }
    }
}
